-- gdTrdTiposDocumentales (Se comenta el tipo documental 0 ya que se encuentra en la base)
-- INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (0,'Sin tipo documental',30,10,to_date('2021-05-06 11:05:11','YYYY-MM-DD HH24:MI:SS'));
-- INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (1,'Formato referencia cruzada','30','10',to_date('2021-06-30 18:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (2,'anexos',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (3,'comunicaciones oficiales',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (4,'actas',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (5,'formato de levantamiento',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (6,'comunicaciones internas',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (7,'comunicaciones externas',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (8,'formatos',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdTiposDocumentales" ("idGdTrdTipoDocumental","nombreTipoDocumental","diasTramiteTipoDocumental","estadoTipoDocumental","creacionTipoDocumental") VALUES (9,'informe',15,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));

-- gdTrdSubseries
INSERT INTO C##ORFEO_USR."gdTrdSubseries" ("idGdTrdSubserie","nombreGdTrdSubserie","codigoGdTrdSubserie","tiempoGestionGdTrdSubserie","tiempoCentralGdTrdSubserie","pSoporteGdTrdSubserie","eSoporteGdTrdSubserie","oSoporteGdTrdSubserie","ctDisposicionFinalGdTrdSubserie","eDisposicionFinalGdTrdSubserie","sDisposicionFinalGdTrdSubserie","mDisposicionFinalGdTrdSubserie","procedimientoGdTrdSubserie","estadoGdTrdSubserie","creacionGdTrdSubserie","normaGdTrdSubserie","idGdTrdSerie") VALUES (1,'Informes a entes de control','001',1,1,0,0,0,0,0,0,10,'Eliminar una vez cumplido el periodo de retención, se elimina porque los originales se administran en unidad de control interno o secretaría general',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),NULL,1);
INSERT INTO C##ORFEO_USR."gdTrdSubseries" ("idGdTrdSubserie","nombreGdTrdSubserie","codigoGdTrdSubserie","tiempoGestionGdTrdSubserie","tiempoCentralGdTrdSubserie","pSoporteGdTrdSubserie","eSoporteGdTrdSubserie","oSoporteGdTrdSubserie","ctDisposicionFinalGdTrdSubserie","eDisposicionFinalGdTrdSubserie","sDisposicionFinalGdTrdSubserie","mDisposicionFinalGdTrdSubserie","procedimientoGdTrdSubserie","estadoGdTrdSubserie","creacionGdTrdSubserie","normaGdTrdSubserie","idGdTrdSerie") VALUES (2,'Informes de gestión','002',1,1,0,0,0,0,0,0,10,'Eliminar una vez cumplido el periodo de retención, se elimina porque los originales se administran en unidad de control interno o secretaría general',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),NULL,1);
INSERT INTO C##ORFEO_USR."gdTrdSubseries" ("idGdTrdSubserie","nombreGdTrdSubserie","codigoGdTrdSubserie","tiempoGestionGdTrdSubserie","tiempoCentralGdTrdSubserie","pSoporteGdTrdSubserie","eSoporteGdTrdSubserie","oSoporteGdTrdSubserie","ctDisposicionFinalGdTrdSubserie","eDisposicionFinalGdTrdSubserie","sDisposicionFinalGdTrdSubserie","mDisposicionFinalGdTrdSubserie","procedimientoGdTrdSubserie","estadoGdTrdSubserie","creacionGdTrdSubserie","normaGdTrdSubserie","idGdTrdSerie") VALUES (3,'Actas','000',2,78,0,0,0,0,0,10,0,'Una vez cumplido el periodo de retención, se seleccionan para conservar aquellas historias laborales de funcionarios mas representativos (de los cargos directivos, asesor y profesional), que por su perfil profesional y  gestión se destaquen por su aporte en el desarrollo institucional de la universidad.',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),NULL,2);
INSERT INTO C##ORFEO_USR."gdTrdSubseries" ("idGdTrdSubserie","nombreGdTrdSubserie","codigoGdTrdSubserie","tiempoGestionGdTrdSubserie","tiempoCentralGdTrdSubserie","pSoporteGdTrdSubserie","eSoporteGdTrdSubserie","oSoporteGdTrdSubserie","ctDisposicionFinalGdTrdSubserie","eDisposicionFinalGdTrdSubserie","sDisposicionFinalGdTrdSubserie","mDisposicionFinalGdTrdSubserie","procedimientoGdTrdSubserie","estadoGdTrdSubserie","creacionGdTrdSubserie","normaGdTrdSubserie","idGdTrdSerie") VALUES (4,'Comunicaciones','001',1,2,0,0,0,10,10,0,10,'Una vez cumplido el periodo de retención, se seleccionan para conservar aquellas historias laborales de funcionarios mas representativos ',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),NULL,3);

-- gdTrdSeries
INSERT INTO C##ORFEO_USR."gdTrdSeries" ("idGdTrdSerie","nombreGdTrdSerie","codigoGdTrdSerie","estadoGdTrdSerie","creacionGdTrdSerie") VALUES (1,'INFORMES','03',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdSeries" ("idGdTrdSerie","nombreGdTrdSerie","codigoGdTrdSerie","estadoGdTrdSerie","creacionGdTrdSerie") VALUES (2,'ACTAS','01',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##ORFEO_USR."gdTrdSeries" ("idGdTrdSerie","nombreGdTrdSerie","codigoGdTrdSerie","estadoGdTrdSerie","creacionGdTrdSerie") VALUES (3,'COMUNICACIONES OFICIALES','02',10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'));

-- gdTrdDependencias (Se utilizan las mismas dependencias de la base por lo cual se comentan)
-- INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrdDependencia","nombreGdTrdDependencia","codigoGdTrdDependencia","codigoGdTrdDepePadre","estadoGdTrdDependencia","creacionGdTrdDependencia","idCgRegional","observacionGdTrdDependencia","consecExpedienteGdTrdDependencia") VALUES (1,'Dependencia de Skinatech','0998',0,10,to_date('2020-08-10 20:29:26','YYYY-MM-DD HH24:MI:SS'),1,'Dependencia de skinatech',1);
-- INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrdDependencia","nombreGdTrdDependencia","codigoGdTrdDependencia","codigoGdTrdDepePadre","estadoGdTrdDependencia","creacionGdTrdDependencia","idCgRegional","observacionGdTrdDependencia","consecExpedienteGdTrdDependencia") VALUES (2,'Dependencia de administración de archivo','0999',0,10,to_date('2020-08-11 08:46:53','YYYY-MM-DD HH24:MI:SS'),1,'Dependencia de administración de archivo',1);

-- orfeo_ng.gdTrd
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (1,1,1,1,1,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (2,1,1,1,2,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (3,1,1,1,3,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (4,1,1,2,1,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (5,1,1,2,2,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (6,1,1,2,3,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (7,1,2,3,4,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (8,1,2,3,3,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (9,1,2,3,5,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (10,1,3,4,6,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (11,1,3,4,7,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (12,1,3,4,2,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
INSERT INTO C##ORFEO_USR."gdTrd" ("idGdTrd","idGdTrdDependencia","idGdTrdSerie","idGdTrdSubserie","idGdTrdTipoDocumental","estadoGdTrd","creacionGdTrd","versionGdTrd","identificadorUnicoGdTrd") VALUES (13,1,3,4,8,10,to_date('2021-05-07 11:45:29','YYYY-MM-DD HH24:MI:SS'),1,'60956ea8556fc');
